name: 'stock_analysis'
version: '1.0.0'
config-version: 2

profile: 'stock_analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stock_analysis:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
